/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/branch/suggest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Generate candidate branches */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["BranchSuggestRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["BranchSuggestResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/branch/confirm": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Confirm or reject candidate branch */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["BranchConfirmRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["BranchConfirmResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tree/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get tree snapshot */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TreeSnapshot"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/node/{id}/edit-question/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Edit a user question and stream the regenerated AI response */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        new_text: string;
                        provider?: string;
                        model?: string;
                        is_byok?: boolean;
                        upload_ids?: string[];
                    };
                };
            };
            responses: {
                /** @description SSE stream of edit-question events */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/event-stream": string;
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/events/replay": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Replay events (used as Undo) - DEPRECATED
         * @deprecated
         * @description WARNING: This endpoint depends on legacy tree_event/tree_node tables which are not used in current dialogue flows.
         *     It is retained for backward compatibility with older tree versions but will not affect nodes/turns in modern trees.
         *     Replacement for "Undo" functionality is pending.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["EventsReplayRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            ok?: boolean;
                            reverted_to?: string;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/memo/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List memo checkpoints */
        get: {
            parameters: {
                query: {
                    tree_id: string;
                    scope_node_id?: string;
                    limit?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["MemoHistoryResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/memo/{memo_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get memo by id */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    memo_id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["MemoGetResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/memo/latest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get latest memo */
        get: {
            parameters: {
                query: {
                    tree_id: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["MemoLatestResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/memo/generate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Generate memo */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["MemoGenerateRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["MemoGenerateResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/outcomes/draft": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Generate or update an outcome outline draft from a resume snapshot */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** @description Resume snapshot ID */
                        snapshot_id: string;
                        /**
                         * @description Outcome draft type (defaults to brief)
                         * @enum {string}
                         */
                        outcome_type?: "decision" | "brief" | "report";
                    };
                };
            };
            responses: {
                /** @description Draft created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            ok?: boolean;
                            draft?: components["schemas"]["OutcomeDraft"];
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/outcomes/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a specific outcome draft by ID */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            draft?: components["schemas"]["OutcomeDraft"];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/outcomes/{id}/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Refresh an outcome draft after evidence updates */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            ok?: boolean;
                            draft?: components["schemas"]["OutcomeDraft"];
                            stats?: {
                                gapCountBefore?: number;
                                gapCountAfter?: number;
                                evidenceCount?: number;
                                evidenceLinks?: number;
                                ledgerAtoms?: number;
                                outlineSectionsBefore?: number;
                                outlineSectionsAfter?: number;
                                requirementsBefore?: number;
                                requirementsAfter?: number;
                                statusPreserved?: number;
                                statusRecomputed?: number;
                                sourcesUpdated?: number;
                                addedSections?: number;
                                mergeConflict?: boolean;
                                mergeConflictKeys?: string[];
                            };
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/outcomes/{id}/export.md": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Export an outcome draft as Markdown with references */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/markdown": string;
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/trees/{treeId}/outcomes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List outcome drafts for a tree */
        get: {
            parameters: {
                query?: {
                    /** @description Filter drafts by snapshot ID */
                    snapshot_id?: string;
                    outcome_type?: "decision" | "brief" | "report";
                    limit?: number;
                };
                header?: never;
                path: {
                    treeId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            drafts?: components["schemas"]["OutcomeDraft"][];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tree/{treeId}/outcomes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List outcomes (v2) for a tree */
        get: {
            parameters: {
                query?: {
                    limit?: number;
                    offset?: number;
                };
                header?: never;
                path: {
                    treeId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            ok?: boolean;
                            outcomes?: components["schemas"]["Outcome"][];
                            limit?: number;
                            offset?: number;
                        };
                    };
                };
            };
        };
        put?: never;
        /** Create an outcome (v2) anchored to a node */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    treeId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["OutcomeCreateRequest"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["OutcomeCreateResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tree/{treeId}/outcomes/preview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Preview outcome (v2) title candidates without creating */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    treeId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["OutcomePreviewRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["OutcomePreviewResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tree/{treeId}/outcomes/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get outcome (v2) details */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    treeId: string;
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["OutcomeDetailResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        /** Delete outcome (v2) */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    treeId: string;
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            ok?: boolean;
                        };
                    };
                };
            };
        };
        options?: never;
        head?: never;
        /** Update outcome (v2) */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    treeId: string;
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["OutcomePatchRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            ok?: boolean;
                            outcome?: components["schemas"]["Outcome"];
                        };
                    };
                };
            };
        };
        trace?: never;
    };
    "/api/tree/{treeId}/outcomes/{id}/regenerate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Regenerate outcome (v2) report_json */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    treeId: string;
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["OutcomeRegenerateResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/evidence": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create an evidence item (url/text) */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["EvidenceCreateRequest"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            ok?: boolean;
                            evidence?: components["schemas"]["EvidenceItem"];
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/evidence/upload": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Upload a file as evidence */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "multipart/form-data": {
                        tree_id: string;
                        title: string;
                        summary?: string;
                        /** @description JSON array string of tags */
                        tags?: string;
                        /** Format: binary */
                        file: string;
                    };
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            ok?: boolean;
                            evidence?: components["schemas"]["EvidenceItem"];
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/evidence/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get evidence details */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            ok?: boolean;
                            evidence?: components["schemas"]["EvidenceItem"];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/evidence/{id}/nodes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List nodes attached to an evidence item */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            ok?: boolean;
                            nodes?: components["schemas"]["EvidenceNodeLink"][];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/trees/{treeId}/evidence": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List evidence for a tree */
        get: {
            parameters: {
                query?: {
                    type?: "url" | "file" | "text";
                    limit?: number;
                    offset?: number;
                };
                header?: never;
                path: {
                    treeId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            ok?: boolean;
                            evidence?: components["schemas"]["EvidenceItem"][];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/nodes/{id}/evidence/{evidenceId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Attach evidence to a node */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                    evidenceId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            ok?: boolean;
                            created?: boolean;
                            link?: components["schemas"]["NodeEvidenceLink"];
                        };
                    };
                };
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            ok?: boolean;
                            created?: boolean;
                            link?: components["schemas"]["NodeEvidenceLink"];
                        };
                    };
                };
            };
        };
        /** Detach evidence from a node */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                    evidenceId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            ok?: boolean;
                            detached?: boolean;
                        };
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/nodes/{id}/evidence": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List evidence attached to a node */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            ok?: boolean;
                            evidence?: components["schemas"]["EvidenceItem"][];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tree/{treeId}/trail": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Generate a new Trail version from keyframes */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    treeId: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        /** @description Optional LLM provider hint */
                        provider?: string;
                        /** @description Optional model override */
                        model?: string;
                    };
                };
            };
            responses: {
                /** @description Trail version created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TrailGenerateResponse"];
                    };
                };
                /** @description No keyframes found */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description LLM generation failed */
                502: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tree/{treeId}/trail/latest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get the latest Trail version for a tree */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    treeId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Latest Trail version (or null if none) */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TrailLatestResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tree/{treeId}/trail/versions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Trail version history with pagination */
        get: {
            parameters: {
                query?: {
                    limit?: number;
                    offset?: number;
                };
                header?: never;
                path: {
                    treeId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Paginated list of Trail versions */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TrailVersionsListResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tree/{treeId}/trail/versions/{versionId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a specific Trail version by ID */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    treeId: string;
                    versionId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Trail version with content */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TrailVersionResponse"];
                    };
                };
                /** @description Version not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tree/{treeId}/path-snapshots": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List PathSnapshots for a tree */
        get: {
            parameters: {
                query?: {
                    limit?: number;
                    offset?: number;
                };
                header?: never;
                path: {
                    treeId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Paginated list of PathSnapshots */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PathSnapshotListResponse"];
                    };
                };
            };
        };
        put?: never;
        /** Create a PathSnapshot from current keyframes */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    treeId: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        /** @description Optional title for the snapshot */
                        title?: string;
                        /**
                         * @default keyframes
                         * @enum {string}
                         */
                        scope?: "keyframes" | "subtree" | "custom";
                    };
                };
            };
            responses: {
                /** @description PathSnapshot created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PathSnapshotCreateResponse"];
                    };
                };
                /** @description No keyframes found */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tree/{treeId}/path-snapshots/latest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get the latest PathSnapshot for a tree */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    treeId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Latest PathSnapshot (or null if none) */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PathSnapshotResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tree/{treeId}/path-snapshots/{snapshotId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a specific PathSnapshot by ID */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    treeId: string;
                    snapshotId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description PathSnapshot with content */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PathSnapshotResponse"];
                    };
                };
                /** @description Snapshot not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        /** Delete a PathSnapshot */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    treeId: string;
                    snapshotId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description PathSnapshot deleted */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            ok?: boolean;
                            /** Format: uuid */
                            deleted?: string;
                        };
                    };
                };
                /** @description Snapshot not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tree/{treeId}/path-snapshots/{snapshotId}/replay": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Get replay data for stepping through a snapshot */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    treeId: string;
                    snapshotId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Replay data with ordered steps */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["PathSnapshotReplayResponse"];
                    };
                };
                /** @description Snapshot not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tree/{treeId}/branch-diff": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Compare two paths and return structured diff points */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    treeId: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["BranchDiffRequest"];
                };
            };
            responses: {
                /** @description Branch diff result with structured points */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["BranchDiffResponse"];
                    };
                };
                /** @description Invalid input */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Node or snapshot not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        TrailVersion: {
            /** Format: uuid */
            id?: string;
            /** Format: date-time */
            created_at?: string;
            prompt_version?: string;
            provider?: string;
            model?: string;
            input?: {
                keyframe_ids?: string[];
                step_count?: number;
                truncation?: Record<string, never>;
            };
            validation_metrics?: {
                stepHeadersFound?: number;
                jumpLinksFound?: number;
                matchedNodeIds?: number;
                hasKeyTakeaways?: boolean;
            };
        };
        TrailGenerateResponse: {
            ok?: boolean;
            version?: components["schemas"]["TrailVersion"];
            content_markdown?: string;
            keyframes_count?: number;
            steps_processed?: number;
            duration_ms?: number;
            validation?: {
                warnings?: string[];
                metrics?: Record<string, never>;
            };
        };
        TrailLatestResponse: {
            ok?: boolean;
            version?: components["schemas"]["TrailVersion"];
            content_markdown?: string | null;
            /** @description True if content is from legacy narrative_report column */
            legacy?: boolean;
            /** Format: date-time */
            updated_at?: string | null;
        };
        TrailVersionSummary: {
            /** Format: uuid */
            id?: string;
            /** Format: date-time */
            created_at?: string;
            prompt_version?: string;
            provider?: string;
            model?: string;
            input?: Record<string, never>;
            content_length?: number;
            step_count?: number | null;
        };
        TrailVersionsListResponse: {
            ok?: boolean;
            versions?: components["schemas"]["TrailVersionSummary"][];
            pagination?: {
                total?: number;
                limit?: number;
                offset?: number;
                has_more?: boolean;
            };
        };
        TrailVersionResponse: {
            ok?: boolean;
            version?: components["schemas"]["TrailVersion"];
            content_markdown?: string;
        };
        PathSnapshot: {
            /** Format: uuid */
            id?: string;
            /** Format: date-time */
            created_at?: string;
            prompt_version?: string;
            title?: string | null;
            keyframe_count?: number;
            node_count?: number;
            input?: {
                title?: string;
                keyframe_ids?: string[];
                node_ids?: string[];
                scope?: string;
                generated_from?: string;
                step_count?: number;
                steps?: components["schemas"]["PathSnapshotStep"][];
            };
        };
        PathSnapshotStep: {
            step_index?: number;
            /** Format: uuid */
            keyframe_id?: string;
            /** Format: uuid */
            node_id?: string;
            /** Format: uuid */
            parent_id?: string | null;
            level?: number;
            role?: string;
            annotation?: string | null;
            /** Format: date-time */
            created_at?: string;
            text_preview?: string;
        };
        PathSnapshotCreateResponse: {
            ok?: boolean;
            snapshot?: {
                /** Format: uuid */
                id?: string;
                /** Format: date-time */
                created_at?: string;
                title?: string;
                keyframe_count?: number;
                node_count?: number;
                scope?: string;
            };
            content_markdown?: string;
        };
        PathSnapshotResponse: {
            ok?: boolean;
            snapshot?: components["schemas"]["PathSnapshot"];
            content_markdown?: string | null;
        };
        PathSnapshotListResponse: {
            ok?: boolean;
            snapshots?: components["schemas"]["PathSnapshot"][];
            pagination?: {
                total?: number;
                limit?: number;
                offset?: number;
                has_more?: boolean;
            };
        };
        PathSnapshotReplayStep: {
            step_index?: number;
            /** Format: uuid */
            node_id?: string;
            annotation?: string | null;
            role?: string;
            text_preview?: string;
            /** @description True if the node still exists */
            is_valid?: boolean;
        };
        PathSnapshotReplayResponse: {
            ok?: boolean;
            /** Format: uuid */
            snapshot_id?: string;
            title?: string | null;
            total_steps?: number;
            valid_steps?: number;
            steps?: components["schemas"]["PathSnapshotReplayStep"][];
            warnings?: string[];
        };
        BranchDiffRequest: {
            /** Format: uuid */
            node_id_a?: string;
            /** Format: uuid */
            node_id_b?: string;
            /** Format: uuid */
            path_snapshot_id_a?: string;
            /** Format: uuid */
            path_snapshot_id_b?: string;
        };
        BranchDiffPoint: {
            summary?: string;
            node_ids_a?: string[];
            node_ids_b?: string[];
            rationale?: string;
        };
        BranchDiffArtifact: {
            /** Format: uuid */
            id?: string;
            /** Format: date-time */
            created_at?: string;
            prompt_version?: string;
            input?: Record<string, never>;
        };
        BranchDiffResponse: {
            ok?: boolean;
            diff?: components["schemas"]["BranchDiffArtifact"];
            diff_points?: components["schemas"]["BranchDiffPoint"][];
            warnings?: {
                [key: string]: unknown;
            }[];
            content_markdown?: string;
        };
        UserSettings: {
            /** @description Whether the user enables advanced context profiles; requires at least one validated BYOK provider. When true, platform default model is disabled. */
            enable_advanced_context?: boolean;
            /** @description Current provider selection; default platform provider is blocked when enable_advanced_context is true. */
            preferred_llm_provider?: string;
        };
        TreeContext: {
            /**
             * @description Context profile for the tree
             * @enum {string}
             */
            context_profile?: "lite" | "standard" | "max";
            /**
             * @description Memory scope for the tree
             * @enum {string}
             */
            memory_scope?: "branch" | "tree";
            /** @description Full tree summary payload (may include provider/model/updated_at) */
            tree_summary?: {
                [key: string]: unknown;
            };
            /** @description Convenience text extracted from tree_summary */
            tree_summary_text?: string;
            /**
             * Format: date-time
             * @description Timestamp of last successful tree summary generation
             */
            tree_summary_updated_at?: string;
            /** @description Last error message from tree summary generation (sanitized) */
            tree_summary_last_error?: string;
            /**
             * Format: date-time
             * @description Timestamp of last tree summary error
             */
            tree_summary_last_error_at?: string;
        };
        BranchSuggestRequest: {
            conversation: string;
            last_node: string;
        };
        BranchSuggestResponse: {
            branch_id: string;
        };
        BranchConfirmRequest: {
            branch_id: string;
            accepted: boolean;
        };
        BranchConfirmResponse: {
            ok: boolean;
        };
        MemoAnchor: {
            type?: string;
            id?: string;
        };
        MemoBullet: {
            text?: string;
            anchors?: components["schemas"]["MemoAnchor"][];
        };
        MemoCoverage: {
            node_count?: number;
            delta_count?: number | null;
        };
        MemoScope: {
            type?: string;
            root_node_id?: string;
        };
        Memo: {
            memo_id?: string;
            /** Format: date-time */
            created_at?: string;
            scope?: components["schemas"]["MemoScope"];
            bullets?: components["schemas"]["MemoBullet"][];
            coverage?: components["schemas"]["MemoCoverage"];
            based_on_memo_id?: string | null;
            lang?: string;
        };
        MemoHistoryItem: {
            memo_id?: string;
            /** Format: date-time */
            created_at?: string;
            lang?: string;
            to_node_seq?: number;
            title?: string;
            first_bullet_preview?: string;
        };
        MemoHistoryMeta: {
            current_max_node_seq?: number;
        };
        MemoHistoryResponse: {
            ok?: boolean;
            history?: components["schemas"]["MemoHistoryItem"][];
            meta?: components["schemas"]["MemoHistoryMeta"];
        };
        MemoGetResponse: {
            ok?: boolean;
            memo?: components["schemas"]["Memo"];
        };
        MemoLatestMeta: {
            current_max_node_seq?: number;
            memo_to_node_seq?: number;
            is_outdated?: boolean;
        };
        MemoLatestResponse: {
            ok?: boolean;
            latest_memo?: components["schemas"]["Memo"];
            meta?: components["schemas"]["MemoLatestMeta"];
        };
        MemoGenerateRequest: {
            tree_id?: string;
            focus_node_id?: string;
            limit_n?: number;
            based_on_memo_id?: string;
            provider?: string;
            model?: string;
            /** @enum {string} */
            lang?: "auto" | "en" | "zh";
        };
        MemoGenerateResponse: {
            ok?: boolean;
            memo?: components["schemas"]["Memo"];
        };
        TreeSnapshot: {
            id?: string;
            title?: string;
            nodes?: {
                [key: string]: unknown;
            }[];
            topic?: string;
            context?: components["schemas"]["TreeContext"];
            /**
             * @description Deprecated: use context.context_profile
             * @enum {string}
             */
            context_profile?: "lite" | "standard" | "max";
            /**
             * @description Deprecated: use context.memory_scope
             * @enum {string}
             */
            memory_scope?: "branch" | "tree";
        };
        EventsReplayRequest: {
            events: {
                [key: string]: unknown;
            }[];
        };
        OutcomeDraft: {
            id?: string;
            tree_id?: string;
            snapshot_id?: string;
            /** @enum {string} */
            outcome_type?: "decision" | "brief" | "report";
            outline_sections?: {
                key?: string;
                title?: string;
                summary?: string;
                sources?: string[];
            }[];
            evidence_requirements?: {
                section_key?: string;
                title?: string;
                needs?: string;
                sources?: string[];
                gaps?: string[];
                status?: string;
            }[];
            gap_count?: number;
            /** Format: date-time */
            created_at?: string;
            /** Format: date-time */
            updated_at?: string;
        };
        Outcome: {
            id?: string;
            user_id?: string;
            tree_id?: string;
            anchor_node_id?: string;
            title?: string;
            conclusion?: string;
            report_json?: {
                [key: string]: unknown;
            };
            derived_from_outcome_id?: string | null;
            /** @enum {string} */
            status?: "generating" | "generated" | "edited";
            prompt_version?: string | null;
            generation_input?: {
                [key: string]: unknown;
            };
            /** Format: date-time */
            created_at?: string;
            /** Format: date-time */
            updated_at?: string;
            asset_published?: boolean;
        };
        OutcomeHighlight: {
            main_path_node_ids?: string[];
            keyframe_node_ids?: string[];
        };
        OutcomeAsset: {
            knowledge_base_id?: string;
            document_id?: string;
            /** Format: date-time */
            updated_at?: string;
        };
        OutcomeCreateRequest: {
            anchor_node_id: string;
            title?: string;
            conclusion?: string;
            /** @description Optional LLM provider hint for title generation */
            provider?: string;
            /** @description Optional model hint for title generation */
            model?: string;
        };
        OutcomePreviewRequest: {
            anchor_node_id: string;
            /** @description Optional one-line conclusion hint for title generation */
            conclusion?: string;
            /** @description Optional LLM provider hint for title generation */
            provider?: string;
            /** @description Optional model hint for title generation */
            model?: string;
        };
        OutcomePreviewResponse: {
            ok?: boolean;
            title_candidates?: string[];
            warning?: string | null;
        };
        OutcomePatchRequest: {
            title?: string;
            conclusion?: string;
        };
        OutcomeCreateResponse: {
            ok?: boolean;
            outcome?: components["schemas"]["Outcome"];
            title_candidates?: string[];
            warning?: string | null;
        };
        OutcomeDetailResponse: {
            ok?: boolean;
            outcome?: components["schemas"]["Outcome"];
            asset?: components["schemas"]["OutcomeAsset"] | null;
            highlight?: components["schemas"]["OutcomeHighlight"];
        };
        OutcomeRegenerateResponse: {
            ok?: boolean;
            outcome?: components["schemas"]["Outcome"];
            warning?: string | null;
        };
        EvidenceItem: {
            id?: string;
            tree_id?: string;
            /** @enum {string} */
            type?: "url" | "file" | "text";
            title?: string;
            summary?: string;
            source_url?: string;
            stored_path?: string;
            text_content?: string;
            file_name?: string;
            file_size?: number;
            mime_type?: string;
            tags?: string[];
            attached_node_count?: number;
            /** Format: date-time */
            created_at?: string;
            /** Format: date-time */
            updated_at?: string;
        };
        EvidenceCreateRequest: {
            tree_id: string;
            /** @enum {string} */
            type: "url" | "file" | "text";
            title: string;
            summary?: string;
            source_url?: string;
            text_content?: string;
            tags?: string[];
        };
        EvidenceNodeLink: {
            id?: string;
            text?: string;
            role?: string;
            /** Format: date-time */
            created_at?: string;
            /** Format: date-time */
            attached_at?: string;
        };
        NodeEvidenceLink: {
            id?: string;
            node_id?: string;
            evidence_id?: string;
            /** Format: date-time */
            created_at?: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
